#!/bin/zsh
# Aliases

alias srz="source ~/.zshrc"

# ---------------------- #
# important directories
# ---------------------- #
alias tmp="cd ~/temp"
alias proj="cd ~/Projects"
alias aud="cd ~/Projects/Audits"
alias play="cd $HOME/Projects/sandbox"
alias cdteam="cd $HOME/Projects/O/monorepo-team"
alias cdpriv="cd $HOME/Projects/O/monorepo-priv"


# --------------------------------- #
# npm/stuff  #
# --------------------------------- #

# Add the local npm binaries to the path, this enables favoring a local
# truffle or testrpc install over the global one.
alias npm-local='PATH=$(npm bin):$PATH'
alias rmnm='echo "running: \$rm -rf node_modules" && rm -rf node_modules \
            && echo "running: \$pnpm" && pnpm'

# pyenv is handled in zpreztorc
export PYENV_VIRTUALENV_DISABLE_PROMPT=1 # this prevents the annoying extra `(mythril`) output
alias pinit='eval "$(pyenv init - --no-rehash zsh)"'
alias p2='pinit && pyenv shell 2.7.9'
# alias p3='pinit && pyenv shell 3.6.1'
alias pam='pyenv activate mythril'
alias pas='pyenv activate shell'
alias paa='pyenv activate analyze'
alias p3='python3'


alias today='date --iso-8601'

# --------------------------------- #
# Open Editor Groups
# --------------------------------- #
alias zshconf="$EDITOR -n $HOME/zprezto/runcoms/zshrc"
alias zpconf="$EDITOR -n $HOME/zprezto/zprezto-config.code-workspace"
alias gconf="$EDITOR -n $HOME/.gitconfig \
  $HOME/.gitignore_global
"

# --------------------------------- #
# terminal utilities
# --------------------------------- #
alias foreach="tr '\n' '\0' | xargs -0 -n1"
alias stripxterm='perl -pe s/e([^[]]|[.*?[a-zA-Z]|].*?a)//g | col -b'

# putting things into the clipboard
alias cpwd='pwd | pbcopy'
alias cplast='history | head -n1 | string replace -r "^\\s*\\d+\\s+" "" | pbcopy'

# ls things
alias al="ls -al"
alias alt='ls -alt'
alias lf='ls -F'
alias lw='ls -al'
alias lsd='ls -ald */'

# Looking around

alias rh='run-help' # another way of running `man` I kind of forget what this does.

# history
alias h='fc -l'
alias thistory='history | grep -v \*' # only history in this session

# make common files easier to read
alias rdme='bat README.md'
alias rdpj='bat package.json'
alias grip='grip -b --quiet --theme=dark'
alias opendot='dot -Tpng | open -fa /Applications/Preview.app'

# find files excluding node_modules
alias fxnm='find . -path **/node_modules -prune -false -o -name'

# --------------------------------- #
# python aliases
# --------------------------------- #
# alias init-pyenv=`eval "$(pyenv init -)"` # && eval "$(pyenv virtualenv-init -)"
alias sba='source venv/bin/activate'
