#!/bin/zsh
# Debugging: uncomment the DEBUG_ZSH_STARTUP export and customize the functions to print a lot of
# output at the start and end of zshenv, zprofile, zshrc, and zprezto (which is also the
# order they run in)
# export DEBUG_ZSH_STARTUP="1"
my_debug_start() {
  if [[ -n "$DEBUG_ZSH_STARTUP" ]]; then
    # print the name of the function that called this function
    echo entering $funcstack[2]
  fi
}

my_debug_end() {
  if [[ -n "$DEBUG_ZSH_STARTUP" ]]; then
    echo exiting $funcstack[2]
    echo PATH is now:
    echo $PATH | grep nix
    # split PATH and get the number of elements
    # local -a path_array
    # path_array=("${(@s/:/)PATH}")
    # echo PATH has ${#path_array} elements
  fi
}

my_debug_start

# This file is sourced by all instances of Zsh, and thus, it should be kept as
# small as possible and should only define environment variables.
#

export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"

# Source my secrets file.
if [[ -s "${ZDOTDIR:-$HOME}/.secrets" ]]; then
  source "${ZDOTDIR:-$HOME}/.secrets"
fi


# Make less show more context when searching
export LESS=j5

export TERM=xterm-256color
export GOPATH=$HOME

export HOMEBREW_PREFIX=/opt/homebrew
# only run this on my optimism machine.
# it makes homebrew work with Apple Silicon somehow.
if [[ -d "/Users/maurelian" ]]; then
  eval $(/opt/homebrew/bin/brew shellenv)
fi

# prepend cargo to path
# Wrap the existing path in the desired order
# The default should be to put things you want access to in ~/bin
export PATH=
$PATH:\
/bin:\
/usr/sbin:\
/sbin:\
/etc/paths.d:\
$GOPATH/bin:\
$HOME/.nvm:\
$HOME/.foundry/bin:\
$HOME/.cargo/bin:\
$HOME/.local/bin:\
"

my_debug_end
