# https://starship.rs/config/
[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[gcloud]
disabled = true

[git_commit]
only_detached = false

[git_status]
staged = '[++\($count\)](green)'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[time]
disabled = false
time_format = '%T'
format = '[\($time\) ]($style)'
style = 'yellow'

[directory]
truncation_length = 3
fish_style_pwd_dir_length = 3
